name: CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run tests
        run: poetry run pytest
